version: '3'

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/db-data
    environment:
      POSTGRES_DB: invoices_production
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5423:5423"

  app:
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    env_file: .env
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_DOMAIN: ${SMTP_DOMAIN}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_AUTHENTICATION: ${SMTP_AUTHENTICATION}
      SMTP_ENABLE_STARTTLS_AUTO: ${SMTP_ENABLE_STARTTLS_AUTO}
      SSO_HOST: ${SSO_HOST}
      SSO_URL: ${SSO_URL}
      SSO_SECRET: ${SSO_SECRET}
      HOSTNAME: ${HOSTNAME}
      RAILS_LOG_TO_STDOUT: 'true'
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"